include_guard()
# insertion_sort
set(INSERTION_SORT_MODULE_NAME "insertion_sort")
set(APP_INSERTION_SORT ${INSERTION_SORT_MODULE_NAME})
set(INSERTION_SORT_DIR_PATH ${CMAKE_SOURCE_DIR}/${INSERTION_SORT_MODULE_NAME})

# merge_sort
set(MERGE_SORT_MODULE_NAME "merge_sort")
set(APP_MERGE_SORT ${MERGE_SORT_MODULE_NAME})
set(MERGE_SORT_DIR_PATH ${CMAKE_SOURCE_DIR}/${MERGE_SORT_MODULE_NAME})

# utils
set(UTILS_MODULE_NAME "utils")
set(LIB_UTILS ${UTILS_MODULE_NAME})
set(UTILS_DIR_PATH ${CMAKE_SOURCE_DIR}/${UTILS_MODULE_NAME})
